<?php
return array(
    'router' => array(
        'routes' => array(
            'crm.rest.auth-ldap' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/auth-ldap[/:auth_ldap_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\AuthLDAP\\Controller',
                    ),
                ),
            ),
            'crm.rest.contatos' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/contatos[/:contatos_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\Contatos\\Controller',
                    ),
                ),
            ),
            'crm.rest.usuarios' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/usuarios[/:usuarios_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\Usuarios\\Controller',
                    ),
                ),
            ),
            'crm.rest.fornecedores' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/fornecedores[/:fornecedores_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\Fornecedores\\Controller',
                    ),
                ),
            ),
            'crm.rest.corretores' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/corretores[/:corretores_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\Corretores\\Controller',
                    ),
                ),
            ),
            'crm.rest.sites' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/sites[/:sites_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\Sites\\Controller',
                    ),
                ),
            ),
            'crm.rest.interacoes' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/interacoes[/:interacoes_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\Interacoes\\Controller',
                    ),
                ),
            ),
            'crm.rest.origens-interacoes' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/origens-interacoes[/:origens_interacoes_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\OrigensInteracoes\\Controller',
                    ),
                ),
            ),
            'crm.rest.situacoes-interacoes' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/situacoes-interacoes[/:situacoes_interacoes_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\SituacoesInteracoes\\Controller',
                    ),
                ),
            ),
            'crm.rest.telefones-contato' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/telefones-contato[/:telefones_contato_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\TelefonesContato\\Controller',
                    ),
                ),
            ),
            'crm.rest.emails-contato' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/emails-contato[/:emails_contato_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\EmailsContato\\Controller',
                    ),
                ),
            ),
            'crm.rest.operadoras' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/operadoras[/:operadoras_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\Operadoras\\Controller',
                    ),
                ),
            ),
            'crm.rest.plantoes' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/plantoes[/:plantoes_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\Plantoes\\Controller',
                    ),
                ),
            ),
            'crm.rest.tipos-plantoes' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/tipos-plantoes[/:tipos_plantoes_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\TiposPlantoes\\Controller',
                    ),
                ),
            ),
            'crm.rest.envio-emails' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/envio-emails[/:envio_emails_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\EnvioEmails\\Controller',
                    ),
                ),
            ),
            'crm.rest.filiais' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/filiais[/:filiais_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\Filiais\\Controller',
                    ),
                ),
            ),
            'crm.rest.permissoes-acesso' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/permissoes-acesso[/:permissoes_acesso_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\PermissoesAcesso\\Controller',
                    ),
                ),
            ),
            'crm.rest.tipos-ligacao' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/tipos-ligacao[/:tipos_ligacao_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\TiposLigacao\\Controller',
                    ),
                ),
            ),
            'crm.rest.tipos-envios' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/tipos-envios[/:tipos_envios_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\TiposEnvios\\Controller',
                    ),
                ),
            ),
            'crm.rest.acl' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/acl[/:acl_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\Acl\\Controller',
                    ),
                ),
            ),
            'crm.rest.agenda-usuario' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/agenda-usuario[/:agenda_usuario_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\AgendaUsuario\\Controller',
                    ),
                ),
            ),
            'crm.rest.cron' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/cron[/:cron_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\Cron\\Controller',
                    ),
                ),
            ),
            'crm.rest.tipo-proposta-operadora' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/tipo-proposta-operadora[/:tipo_proposta_operadora_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\TipoPropostaOperadora\\Controller',
                    ),
                ),
            ),
            'crm.rest.gesto-nacional-dash-board' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/gesto-nacional-dash-board[/:gesto_nacional_dash_board_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\GestoNacionalDashBoard\\Controller',
                    ),
                ),
            ),
            'crm.rest.contato-corretor-bloqueio' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/contato-corretor-bloqueio[/:contato_corretor_bloqueio_id]',
                    'defaults' => array(
                        'controller' => 'crm\\V1\\Rest\\ContatoCorretorBloqueio\\Controller',
                    ),
                ),
            ),
        ),
    ),
    'zf-versioning' => array(
        'uri' => array(
            1 => 'crm.rest.auth-ldap',
            0 => 'crm.rest.contatos',
            2 => 'crm.rest.usuarios',
            3 => 'crm.rest.fornecedores',
            4 => 'crm.rest.corretores',
            7 => 'crm.rest.sites',
            8 => 'crm.rest.interacoes',
            9 => 'crm.rest.origens-interacoes',
            10 => 'crm.rest.situacoes-interacoes',
            11 => 'crm.rest.telefones-contato',
            12 => 'crm.rest.emails-contato',
            13 => 'crm.rest.operadoras',
            14 => 'crm.rest.plantoes',
            15 => 'crm.rest.tipos-plantoes',
            17 => 'crm.rest.envio-emails',
            18 => 'crm.rest.filiais',
            19 => 'crm.rest.permissoes-acesso',
            20 => 'crm.rest.tipos-ligacao',
            21 => 'crm.rest.tipos-envios',
            22 => 'crm.rest.acl',
            23 => 'crm.rest.agenda-usuario',
            24 => 'crm.rest.cron',
            25 => 'crm.rest.tipo-proposta-operadora',
            26 => 'crm.rest.gesto-nacional-dash-board',
            27 => 'crm.rest.contato-corretor-bloqueio',
        ),
    ),
    'zf-rest' => array(
        'crm\\V1\\Rest\\AuthLDAP\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\AuthLDAP\\AuthLDAPResource',
            'route_name' => 'crm.rest.auth-ldap',
            'route_identifier_name' => 'auth_ldap_id',
            'collection_name' => 'auth_ldap',
            'entity_http_methods' => array(
                0 => 'PUT',
                1 => 'POST',
                2 => 'GET',
                3 => 'DELETE',
                4 => 'PATCH',
            ),
            'collection_http_methods' => array(
                0 => 'POST',
                1 => 'GET',
                2 => 'PATCH',
                3 => 'DELETE',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\AuthLDAP\\AuthLDAPEntity',
            'collection_class' => 'crm\\V1\\Rest\\AuthLDAP\\AuthLDAPCollection',
            'service_name' => 'authLDAP',
        ),
        'crm\\V1\\Rest\\Contatos\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\Contatos\\ContatosResource',
            'route_name' => 'crm.rest.contatos',
            'route_identifier_name' => 'contatos_id',
            'collection_name' => 'contatos',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'nome',
                1 => 'email',
                2 => 'telefone',
                3 => 'tipo',
                4 => 'termo',
                5 => 'groupBy',
                6 => 'idContato',
                7 => 'dataInicio',
                8 => 'dataFim',
                9 => 'tipoPlantao',
                10 => 'corretorId',
            ),
            'page_size' => '25',
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\Contatos\\ContatosEntity',
            'collection_class' => 'crm\\V1\\Rest\\Contatos\\ContatosCollection',
            'service_name' => 'contatos',
        ),
        'crm\\V1\\Rest\\Usuarios\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\Usuarios\\UsuariosResource',
            'route_name' => 'crm.rest.usuarios',
            'route_identifier_name' => 'usuarios_id',
            'collection_name' => 'usuarios',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'POST',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'email',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\Entity\\Usuarios',
            'collection_class' => 'crm\\V1\\Rest\\Usuarios\\UsuariosCollection',
            'service_name' => 'usuarios',
        ),
        'crm\\V1\\Rest\\Fornecedores\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\Fornecedores\\FornecedoresResource',
            'route_name' => 'crm.rest.fornecedores',
            'route_identifier_name' => 'fornecedores_id',
            'collection_name' => 'fornecedores',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\Fornecedores\\FornecedoresEntity',
            'collection_class' => 'crm\\V1\\Rest\\Fornecedores\\FornecedoresCollection',
            'service_name' => 'fornecedores',
        ),
        'crm\\V1\\Rest\\Corretores\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\Corretores\\CorretoresResource',
            'route_name' => 'crm.rest.corretores',
            'route_identifier_name' => 'corretores_id',
            'collection_name' => 'corretores',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'tipo',
                1 => 'termo',
                2 => 'filialId',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\Corretores\\CorretoresEntity',
            'collection_class' => 'crm\\V1\\Rest\\Corretores\\CorretoresCollection',
            'service_name' => 'corretores',
        ),
        'crm\\V1\\Rest\\Sites\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\Sites\\SitesResource',
            'route_name' => 'crm.rest.sites',
            'route_identifier_name' => 'sites_id',
            'collection_name' => 'sites',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\Sites\\SitesEntity',
            'collection_class' => 'crm\\V1\\Rest\\Sites\\SitesCollection',
            'service_name' => 'sites',
        ),
        'crm\\V1\\Rest\\Interacoes\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\Interacoes\\InteracoesResource',
            'route_name' => 'crm.rest.interacoes',
            'route_identifier_name' => 'interacoes_id',
            'collection_name' => 'interacoes',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
            ),
            'collection_query_whitelist' => array(
                0 => 'corretorId',
                1 => 'interacaoId',
                2 => 'idContato',
                3 => 'nome',
                4 => 'telefone',
                5 => 'email',
                6 => 'idOperadora',
                7 => 'idStatus',
                8 => 'tipoEnvio',
                9 => 'dataInicio',
                10 => 'dataFim',
                11 => 'origemTipo',
                12 => 'idOrigem',
                13 => 'pmePf',
                14 => 'empresa',
                15 => 'inativos',
                16 => 'tipo',
                17 => 'idFilial',
                18 => 'groupBy',
                19 => 'arrayDashGestor',
                20 => 'dashGestorNacional',
                21 => 'respondidas',
                22 => 'filialId',
            ),
            'page_size' => '5',
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\Interacoes\\InteracoesEntity',
            'collection_class' => 'crm\\V1\\Rest\\Interacoes\\InteracoesCollection',
            'service_name' => 'interacoes',
        ),
        'crm\\V1\\Rest\\OrigensInteracoes\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\OrigensInteracoes\\OrigensInteracoesResource',
            'route_name' => 'crm.rest.origens-interacoes',
            'route_identifier_name' => 'origens_interacoes_id',
            'collection_name' => 'origens_interacoes',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\OrigensInteracoes\\OrigensInteracoesEntity',
            'collection_class' => 'crm\\V1\\Rest\\OrigensInteracoes\\OrigensInteracoesCollection',
            'service_name' => 'origensInteracoes',
        ),
        'crm\\V1\\Rest\\SituacoesInteracoes\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\SituacoesInteracoes\\SituacoesInteracoesResource',
            'route_name' => 'crm.rest.situacoes-interacoes',
            'route_identifier_name' => 'situacoes_interacoes_id',
            'collection_name' => 'situacoes_interacoes',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\SituacoesInteracoes\\SituacoesInteracoesEntity',
            'collection_class' => 'crm\\V1\\Rest\\SituacoesInteracoes\\SituacoesInteracoesCollection',
            'service_name' => 'situacoesInteracoes',
        ),
        'crm\\V1\\Rest\\TelefonesContato\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\TelefonesContato\\TelefonesContatoResource',
            'route_name' => 'crm.rest.telefones-contato',
            'route_identifier_name' => 'telefones_contato_id',
            'collection_name' => 'telefones_contato',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\TelefonesContato\\TelefonesContatoEntity',
            'collection_class' => 'crm\\V1\\Rest\\TelefonesContato\\TelefonesContatoCollection',
            'service_name' => 'telefonesContato',
        ),
        'crm\\V1\\Rest\\EmailsContato\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\EmailsContato\\EmailsContatoResource',
            'route_name' => 'crm.rest.emails-contato',
            'route_identifier_name' => 'emails_contato_id',
            'collection_name' => 'emails_contato',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\EmailsContato\\EmailsContatoEntity',
            'collection_class' => 'crm\\V1\\Rest\\EmailsContato\\EmailsContatoCollection',
            'service_name' => 'emailsContato',
        ),
        'crm\\V1\\Rest\\Operadoras\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\Operadoras\\OperadorasResource',
            'route_name' => 'crm.rest.operadoras',
            'route_identifier_name' => 'operadoras_id',
            'collection_name' => 'operadoras',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\Operadoras\\OperadorasEntity',
            'collection_class' => 'crm\\V1\\Rest\\Operadoras\\OperadorasCollection',
            'service_name' => 'operadoras',
        ),
        'crm\\V1\\Rest\\Plantoes\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\Plantoes\\PlantoesResource',
            'route_name' => 'crm.rest.plantoes',
            'route_identifier_name' => 'plantoes_id',
            'collection_name' => 'plantoes',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'DELETE',
            ),
            'collection_query_whitelist' => array(
                0 => 'tipo',
                1 => 'termo',
                2 => 'tipoPlantao',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\Plantoes\\PlantoesEntity',
            'collection_class' => 'crm\\V1\\Rest\\Plantoes\\PlantoesCollection',
            'service_name' => 'plantoes',
        ),
        'crm\\V1\\Rest\\TiposPlantoes\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\TiposPlantoes\\TiposPlantoesResource',
            'route_name' => 'crm.rest.tipos-plantoes',
            'route_identifier_name' => 'tipos_plantoes_id',
            'collection_name' => 'tipos_plantoes',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\TiposPlantoes\\TiposPlantoesEntity',
            'collection_class' => 'crm\\V1\\Rest\\TiposPlantoes\\TiposPlantoesCollection',
            'service_name' => 'tiposPlantoes',
        ),
        'crm\\V1\\Rest\\EnvioEmails\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\EnvioEmails\\EnvioEmailsResource',
            'route_name' => 'crm.rest.envio-emails',
            'route_identifier_name' => 'envio_emails_id',
            'collection_name' => 'envio_emails',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\EnvioEmails\\EnvioEmailsEntity',
            'collection_class' => 'crm\\V1\\Rest\\EnvioEmails\\EnvioEmailsCollection',
            'service_name' => 'envioEmails',
        ),
        'crm\\V1\\Rest\\Filiais\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\Filiais\\FiliaisResource',
            'route_name' => 'crm.rest.filiais',
            'route_identifier_name' => 'filiais_id',
            'collection_name' => 'filiais',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\Filiais\\FiliaisEntity',
            'collection_class' => 'crm\\V1\\Rest\\Filiais\\FiliaisCollection',
            'service_name' => 'filiais',
        ),
        'crm\\V1\\Rest\\PermissoesAcesso\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\PermissoesAcesso\\PermissoesAcessoResource',
            'route_name' => 'crm.rest.permissoes-acesso',
            'route_identifier_name' => 'permissoes_acesso_id',
            'collection_name' => 'permissoes_acesso',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'idPerfil',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\PermissoesAcesso\\PermissoesAcessoEntity',
            'collection_class' => 'crm\\V1\\Rest\\PermissoesAcesso\\PermissoesAcessoCollection',
            'service_name' => 'permissoesAcesso',
        ),
        'crm\\V1\\Rest\\TiposLigacao\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\TiposLigacao\\TiposLigacaoResource',
            'route_name' => 'crm.rest.tipos-ligacao',
            'route_identifier_name' => 'tipos_ligacao_id',
            'collection_name' => 'tipos_ligacao',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\TiposLigacao\\TiposLigacaoEntity',
            'collection_class' => 'crm\\V1\\Rest\\TiposLigacao\\TiposLigacaoCollection',
            'service_name' => 'tiposLigacao',
        ),
        'crm\\V1\\Rest\\TiposEnvios\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\TiposEnvios\\TiposEnviosResource',
            'route_name' => 'crm.rest.tipos-envios',
            'route_identifier_name' => 'tipos_envios_id',
            'collection_name' => 'tipos_envios',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\TiposEnvios\\TiposEnviosEntity',
            'collection_class' => 'crm\\V1\\Rest\\TiposEnvios\\TiposEnviosCollection',
            'service_name' => 'tiposEnvios',
        ),
        'crm\\V1\\Rest\\Acl\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\Acl\\AclResource',
            'route_name' => 'crm.rest.acl',
            'route_identifier_name' => 'acl_id',
            'collection_name' => 'acl',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'tipo',
                1 => 'idPerfil',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\Acl\\AclEntity',
            'collection_class' => 'crm\\V1\\Rest\\Acl\\AclCollection',
            'service_name' => 'acl',
        ),
        'crm\\V1\\Rest\\AgendaUsuario\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\AgendaUsuario\\AgendaUsuarioResource',
            'route_name' => 'crm.rest.agenda-usuario',
            'route_identifier_name' => 'agenda_usuario_id',
            'collection_name' => 'agenda_usuario',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'DELETE',
                2 => 'POST',
                3 => 'PUT',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'DELETE',
            ),
            'collection_query_whitelist' => array(
                0 => 'idUsuario',
                1 => 'tipo',
                2 => 'dataInicio',
                3 => 'dataFim',
                4 => 'inativos',
                5 => 'concluidos',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\AgendaUsuario\\AgendaUsuarioEntity',
            'collection_class' => 'crm\\V1\\Rest\\AgendaUsuario\\AgendaUsuarioCollection',
            'service_name' => 'agendaUsuario',
        ),
        'crm\\V1\\Rest\\Cron\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\Cron\\CronResource',
            'route_name' => 'crm.rest.cron',
            'route_identifier_name' => 'cron_id',
            'collection_name' => 'cron',
            'entity_http_methods' => array(
                0 => 'GET',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
            ),
            'collection_query_whitelist' => array(
                0 => 'cron',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\Cron\\CronEntity',
            'collection_class' => 'crm\\V1\\Rest\\Cron\\CronCollection',
            'service_name' => 'cron',
        ),
        'crm\\V1\\Rest\\TipoPropostaOperadora\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\TipoPropostaOperadora\\TipoPropostaOperadoraResource',
            'route_name' => 'crm.rest.tipo-proposta-operadora',
            'route_identifier_name' => 'tipo_proposta_operadora_id',
            'collection_name' => 'tipo_proposta_operadora',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\TipoPropostaOperadora\\TipoPropostaOperadoraEntity',
            'collection_class' => 'crm\\V1\\Rest\\TipoPropostaOperadora\\TipoPropostaOperadoraCollection',
            'service_name' => 'tipoPropostaOperadora',
        ),
        'crm\\V1\\Rest\\GestoNacionalDashBoard\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\GestoNacionalDashBoard\\GestoNacionalDashBoardResource',
            'route_name' => 'crm.rest.gesto-nacional-dash-board',
            'route_identifier_name' => 'gesto_nacional_dash_board_id',
            'collection_name' => 'gesto_nacional_dash_board',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'tipo',
                1 => 'dataFim',
                2 => 'dataInicio',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\GestoNacionalDashBoard\\GestoNacionalDashBoardEntity',
            'collection_class' => 'crm\\V1\\Rest\\GestoNacionalDashBoard\\GestoNacionalDashBoardCollection',
            'service_name' => 'gestoNacionalDashBoard',
        ),
        'crm\\V1\\Rest\\ContatoCorretorBloqueio\\Controller' => array(
            'listener' => 'crm\\V1\\Rest\\ContatoCorretorBloqueio\\ContatoCorretorBloqueioResource',
            'route_name' => 'crm.rest.contato-corretor-bloqueio',
            'route_identifier_name' => 'contato_corretor_bloqueio_id',
            'collection_name' => 'contato_corretor_bloqueio',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'tipo',
                1 => 'idContato',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\ContatoCorretorBloqueio\\ContatoCorretorBloqueioEntity',
            'collection_class' => 'crm\\V1\\Rest\\ContatoCorretorBloqueio\\ContatoCorretorBloqueioCollection',
            'service_name' => 'contatoCorretorBloqueio',
        ),
    ),
    'zf-content-negotiation' => array(
        'controllers' => array(
            'crm\\V1\\Rest\\AuthLDAP\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Contatos\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Usuarios\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Fornecedores\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Corretores\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Sites\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Interacoes\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\OrigensInteracoes\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\SituacoesInteracoes\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\TelefonesContato\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\EmailsContato\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Operadoras\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Plantoes\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\TiposPlantoes\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\EnvioEmails\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Filiais\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\PermissoesAcesso\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\TiposLigacao\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\TiposEnvios\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Acl\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\AgendaUsuario\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Cron\\Controller' => 'Json',
            'crm\\V1\\Rest\\TipoPropostaOperadora\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\GestoNacionalDashBoard\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\ContatoCorretorBloqueio\\Controller' => 'HalJson',
        ),
        'accept_whitelist' => array(
            'crm\\V1\\Rest\\AuthLDAP\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\Contatos\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\Usuarios\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\Fornecedores\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\Corretores\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\Sites\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\Interacoes\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\OrigensInteracoes\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\SituacoesInteracoes\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\TelefonesContato\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\EmailsContato\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\Operadoras\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\Plantoes\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\TiposPlantoes\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\EnvioEmails\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\Filiais\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\PermissoesAcesso\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\TiposLigacao\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\TiposEnvios\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\Acl\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\AgendaUsuario\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\Cron\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\TipoPropostaOperadora\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\GestoNacionalDashBoard\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'crm\\V1\\Rest\\ContatoCorretorBloqueio\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
        ),
        'content_type_whitelist' => array(
            'crm\\V1\\Rest\\AuthLDAP\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\Contatos\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\Usuarios\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\Fornecedores\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\Corretores\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\Sites\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\Interacoes\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\OrigensInteracoes\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\SituacoesInteracoes\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\TelefonesContato\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\EmailsContato\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\Operadoras\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\Plantoes\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\TiposPlantoes\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\EnvioEmails\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\Filiais\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\PermissoesAcesso\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\TiposLigacao\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\TiposEnvios\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\Acl\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\AgendaUsuario\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\Cron\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\TipoPropostaOperadora\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\GestoNacionalDashBoard\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
            'crm\\V1\\Rest\\ContatoCorretorBloqueio\\Controller' => array(
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ),
        ),
    ),
    'zf-hal' => array(
        'metadata_map' => array(
            'crm\\V1\\Rest\\AuthLDAP\\AuthLDAPEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.auth-ldap',
                'route_identifier_name' => 'auth_ldap_id',
                'hydrator' => 'DoctrineModule\\Stdlib\\Hydrator\\DoctrineObject',
            ),
            'crm\\V1\\Rest\\AuthLDAP\\AuthLDAPCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.auth-ldap',
                'route_identifier_name' => 'auth_ldap_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\Contatos\\ContatosEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.contatos',
                'route_identifier_name' => 'contatos_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\Contatos\\ContatosCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.contatos',
                'route_identifier_name' => 'contatos_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\Usuarios\\UsuariosEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.usuarios',
                'route_identifier_name' => 'usuarios_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\Usuarios\\UsuariosCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.usuarios',
                'route_identifier_name' => 'usuarios_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\Entity\\Usuarios' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.usuarios',
                'route_identifier_name' => 'usuarios_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\Fornecedores\\FornecedoresEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.fornecedores',
                'route_identifier_name' => 'fornecedores_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\Fornecedores\\FornecedoresCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.fornecedores',
                'route_identifier_name' => 'fornecedores_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\Corretores\\CorretoresEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.corretores',
                'route_identifier_name' => 'corretores_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\Corretores\\CorretoresCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.corretores',
                'route_identifier_name' => 'corretores_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\Sites\\SitesEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.sites',
                'route_identifier_name' => 'sites_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\Sites\\SitesCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.sites',
                'route_identifier_name' => 'sites_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\Interacoes\\InteracoesEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.interacoes',
                'route_identifier_name' => 'interacoes_id',
                'hydrator' => 'DoctrineModule\\Stdlib\\Hydrator\\DoctrineObject',
            ),
            'crm\\V1\\Rest\\Interacoes\\InteracoesCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.interacoes',
                'route_identifier_name' => 'interacoes_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\OrigensInteracoes\\OrigensInteracoesEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.origens-interacoes',
                'route_identifier_name' => 'origens_interacoes_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\OrigensInteracoes\\OrigensInteracoesCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.origens-interacoes',
                'route_identifier_name' => 'origens_interacoes_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\SituacoesInteracoes\\SituacoesInteracoesEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.situacoes-interacoes',
                'route_identifier_name' => 'situacoes_interacoes_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\SituacoesInteracoes\\SituacoesInteracoesCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.situacoes-interacoes',
                'route_identifier_name' => 'situacoes_interacoes_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\TelefonesContato\\TelefonesContatoEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.telefones-contato',
                'route_identifier_name' => 'telefones_contato_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\TelefonesContato\\TelefonesContatoCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.telefones-contato',
                'route_identifier_name' => 'telefones_contato_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\EmailsContato\\EmailsContatoEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.emails-contato',
                'route_identifier_name' => 'emails_contato_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\EmailsContato\\EmailsContatoCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.emails-contato',
                'route_identifier_name' => 'emails_contato_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\Operadoras\\OperadorasEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.operadoras',
                'route_identifier_name' => 'operadoras_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\Operadoras\\OperadorasCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.operadoras',
                'route_identifier_name' => 'operadoras_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\Plantoes\\PlantoesEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.plantoes',
                'route_identifier_name' => 'plantoes_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\Plantoes\\PlantoesCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.plantoes',
                'route_identifier_name' => 'plantoes_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\TiposPlantoes\\TiposPlantoesEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.tipos-plantoes',
                'route_identifier_name' => 'tipos_plantoes_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\TiposPlantoes\\TiposPlantoesCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.tipos-plantoes',
                'route_identifier_name' => 'tipos_plantoes_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\EnvioEmails\\EnvioEmailsEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.envio-emails',
                'route_identifier_name' => 'envio_emails_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\EnvioEmails\\EnvioEmailsCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.envio-emails',
                'route_identifier_name' => 'envio_emails_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\Filiais\\FiliaisEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.filiais',
                'route_identifier_name' => 'filiais_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\Filiais\\FiliaisCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.filiais',
                'route_identifier_name' => 'filiais_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\PermissoesAcesso\\PermissoesAcessoEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.permissoes-acesso',
                'route_identifier_name' => 'permissoes_acesso_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\PermissoesAcesso\\PermissoesAcessoCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.permissoes-acesso',
                'route_identifier_name' => 'permissoes_acesso_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\TiposLigacao\\TiposLigacaoEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.tipos-ligacao',
                'route_identifier_name' => 'tipos_ligacao_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\TiposLigacao\\TiposLigacaoCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.tipos-ligacao',
                'route_identifier_name' => 'tipos_ligacao_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\TiposEnvios\\TiposEnviosEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.tipos-envios',
                'route_identifier_name' => 'tipos_envios_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\TiposEnvios\\TiposEnviosCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.tipos-envios',
                'route_identifier_name' => 'tipos_envios_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\Acl\\AclEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.acl',
                'route_identifier_name' => 'acl_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\Acl\\AclCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.acl',
                'route_identifier_name' => 'acl_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\AgendaUsuario\\AgendaUsuarioEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.agenda-usuario',
                'route_identifier_name' => 'agenda_usuario_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\AgendaUsuario\\AgendaUsuarioCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.agenda-usuario',
                'route_identifier_name' => 'agenda_usuario_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\Cron\\CronEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.cron',
                'route_identifier_name' => 'cron_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\Cron\\CronCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.cron',
                'route_identifier_name' => 'cron_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\TipoPropostaOperadora\\TipoPropostaOperadoraEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.tipo-proposta-operadora',
                'route_identifier_name' => 'tipo_proposta_operadora_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\TipoPropostaOperadora\\TipoPropostaOperadoraCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.tipo-proposta-operadora',
                'route_identifier_name' => 'tipo_proposta_operadora_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\GestoNacionalDashBoard\\GestoNacionalDashBoardEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.gesto-nacional-dash-board',
                'route_identifier_name' => 'gesto_nacional_dash_board_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\GestoNacionalDashBoard\\GestoNacionalDashBoardCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.gesto-nacional-dash-board',
                'route_identifier_name' => 'gesto_nacional_dash_board_id',
                'is_collection' => true,
            ),
            'crm\\V1\\Rest\\ContatoCorretorBloqueio\\ContatoCorretorBloqueioEntity' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.contato-corretor-bloqueio',
                'route_identifier_name' => 'contato_corretor_bloqueio_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'crm\\V1\\Rest\\ContatoCorretorBloqueio\\ContatoCorretorBloqueioCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.contato-corretor-bloqueio',
                'route_identifier_name' => 'contato_corretor_bloqueio_id',
                'is_collection' => true,
            ),
        ),
    ),
    'zf-apigility' => array(
        'db-connected' => array(),
    ),
    'zf-content-validation' => array(
        'crm\\V1\\Rest\\AuthLDAP\\Controller' => array(
            'input_filter' => 'crm\\V1\\Rest\\AuthLDAP\\Validator',
        ),
        'crm\\V1\\Rest\\Contatos\\Controller' => array(
            'input_filter' => 'crm\\V1\\Rest\\Contatos\\Validator',
        ),
        'crm\\V1\\Rest\\Cron\\Controller' => array(
            'input_filter' => 'crm\\V1\\Rest\\Cron\\Validator',
        ),
    ),
    'input_filter_specs' => array(
        'crm\\V1\\Rest\\AuthLDAP\\Validator' => array(
            0 => array(
                'required' => true,
                'validators' => array(),
                'filters' => array(),
                'name' => 'usuario',
                'description' => 'Usuário do AD.',
                'error_message' => 'Informe o usuário.',
            ),
            1 => array(
                'required' => true,
                'validators' => array(),
                'filters' => array(),
                'name' => 'password',
                'description' => 'Senha do usuario no Ad.',
                'error_message' => 'Informe a senha utilizada para logar no Ad.',
            ),
        ),
        'crm\\V1\\Rest\\Contatos\\Validator' => array(
            0 => array(
                'required' => true,
                'validators' => array(),
                'filters' => array(),
                'name' => 'nome',
                'description' => 'Nome do contato.',
                'error_message' => 'O nome é obrigatório.',
            ),
            1 => array(
                'required' => false,
                'validators' => array(),
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\ToInt',
                        'options' => array(),
                    ),
                ),
                'name' => 'idade',
                'description' => 'Idade do contato, pode ser nulo.',
            ),
            2 => array(
                'required' => false,
                'validators' => array(),
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\ToInt',
                        'options' => array(),
                    ),
                ),
                'name' => 'origemTipo',
                'description' => 'Tipo da origem : sites, fornecedores, outras.',
                'error_message' => 'O tipo da origem é obrigatório.',
            ),
            3 => array(
                'required' => false,
                'validators' => array(),
                'filters' => array(),
                'name' => 'origem',
                'description' => '"origem": {
                    "id":1
                },
                 ID da origem.(valor fixo de acordo com o fornecedor)',
                'error_message' => 'Informe o ID da origem',
            ),
            4 => array(
                'required' => false,
                'validators' => array(),
                'filters' => array(),
                'name' => 'Observação',
                'description' => 'Observação a respeito do contato. 
                    Pode ser nulo',
            ),
            5 => array(
                'required' => true,
                'validators' => array(),
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\ToInt',
                        'options' => array(),
                    ),
                ),
                'name' => 'situacao',
                'description' => 'Situação do contato, valor padrão  1.',
                'error_message' => 'Informe a situação',
            ),
            6 => array(
                'required' => true,
                'validators' => array(),
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\ToInt',
                        'options' => array(),
                    ),
                ),
                'name' => 'idUsuarioCad',
                'description' => 'Identificador do usuário que está efetuado o cadastro.',
                'error_message' => 'Informe o Id do usuário.',
            ),
            7 => array(
                'required' => false,
                'validators' => array(),
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\ToInt',
                        'options' => array(),
                    ),
                ),
                'name' => 'idOperadora',
                'description' => 'Identificador da operada. Pode ser nulo.',
            ),
            8 => array(
                'required' => false,
                'validators' => array(),
                'filters' => array(),
                'name' => 'tipo',
                'description' => 'Valores padrões \'pme\' e \'pf\'',
                'error_message' => 'Informe o tipo: PF ou PME',
            ),
            9 => array(
                'required' => false,
                'validators' => array(),
                'filters' => array(),
                'name' => 'telefones',
                'description' => 'Os telefones devem vir em formato de array sem mascara : 
                "telefones":[
                   {
                    "identify":"telefone",
                    "telefone":"31234222233"
                    }
                ]',
            ),
            10 => array(
                'required' => false,
                'validators' => array(),
                'filters' => array(),
                'name' => 'emails',
                'description' => 'Emails do contato, pode ser nullo:

                "emails":[{"identify":"email","email":"teste@teste.com"}]',
            ),
        ),
        'crm\\V1\\Rest\\Cron\\Validator' => array(
            0 => array(
                'required' => true,
                'validators' => array(),
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringToLower',
                        'options' => array(),
                    ),
                ),
                'name' => 'cron',
                'description' => 'Cron a  ser executado.',
                'error_message' => 'Informe qual rotina deseja executar.',
            ),
        ),
    ),
    'doctrine' => array(
        'driver' => array(
            'crm_driver' => array(
                'class' => 'Doctrine\\ORM\\Mapping\\Driver\\AnnotationDriver',
                'cache' => 'array',
                'paths' => array(
                    0 => './module/crm/src/crm/Entity',
                ),
            ),
            'orm_default' => array(
                'drivers' => array(
                    'crm\\Entity' => 'crm_driver',
                ),
            ),
        ),
    ),
    'service_manager' => array(
        'factories' => array(
            'crm\\V1\\Rest\\AuthLDAP\\AuthLDAPResource' => 'crm\\V1\\Rest\\AuthLDAP\\AuthLDAPResourceFactory',
            'crm\\V1\\Rest\\Contatos\\ContatosResource' => 'crm\\V1\\Rest\\Contatos\\ContatosResourceFactory',
            'crm\\V1\\Rest\\Usuarios\\UsuariosResource' => 'crm\\V1\\Rest\\Usuarios\\UsuariosResourceFactory',
            'crm\\V1\\Rest\\Fornecedores\\FornecedoresResource' => 'crm\\V1\\Rest\\Fornecedores\\FornecedoresResourceFactory',
            'crm\\V1\\Rest\\Corretores\\CorretoresResource' => 'crm\\V1\\Rest\\Corretores\\CorretoresResourceFactory',
            'crm\\V1\\Rest\\Sites\\SitesResource' => 'crm\\V1\\Rest\\Sites\\SitesResourceFactory',
            'crm\\V1\\Rest\\Interacoes\\InteracoesResource' => 'crm\\V1\\Rest\\Interacoes\\InteracoesResourceFactory',
            'crm\\V1\\Rest\\OrigensInteracoes\\OrigensInteracoesResource' => 'crm\\V1\\Rest\\OrigensInteracoes\\OrigensInteracoesResourceFactory',
            'crm\\V1\\Rest\\SituacoesInteracoes\\SituacoesInteracoesResource' => 'crm\\V1\\Rest\\SituacoesInteracoes\\SituacoesInteracoesResourceFactory',
            'crm\\V1\\Rest\\TelefonesContato\\TelefonesContatoResource' => 'crm\\V1\\Rest\\TelefonesContato\\TelefonesContatoResourceFactory',
            'crm\\V1\\Rest\\EmailsContato\\EmailsContatoResource' => 'crm\\V1\\Rest\\EmailsContato\\EmailsContatoResourceFactory',
            'crm\\V1\\Rest\\Operadoras\\OperadorasResource' => 'crm\\V1\\Rest\\Operadoras\\OperadorasResourceFactory',
            'crm\\V1\\Rest\\Plantoes\\PlantoesResource' => 'crm\\V1\\Rest\\Plantoes\\PlantoesResourceFactory',
            'crm\\V1\\Rest\\TiposPlantoes\\TiposPlantoesResource' => 'crm\\V1\\Rest\\TiposPlantoes\\TiposPlantoesResourceFactory',
            'crm\\V1\\Rest\\EnvioEmails\\EnvioEmailsResource' => 'crm\\V1\\Rest\\EnvioEmails\\EnvioEmailsResourceFactory',
            'crm\\V1\\Rest\\Filiais\\FiliaisResource' => 'crm\\V1\\Rest\\Filiais\\FiliaisResourceFactory',
            'crm\\V1\\Rest\\PermissoesAcesso\\PermissoesAcessoResource' => 'crm\\V1\\Rest\\PermissoesAcesso\\PermissoesAcessoResourceFactory',
            'crm\\V1\\Rest\\TiposLigacao\\TiposLigacaoResource' => 'crm\\V1\\Rest\\TiposLigacao\\TiposLigacaoResourceFactory',
            'crm\\V1\\Rest\\TiposEnvios\\TiposEnviosResource' => 'crm\\V1\\Rest\\TiposEnvios\\TiposEnviosResourceFactory',
            'crm\\V1\\Rest\\Acl\\AclResource' => 'crm\\V1\\Rest\\Acl\\AclResourceFactory',
            'crm\\V1\\Rest\\AgendaUsuario\\AgendaUsuarioResource' => 'crm\\V1\\Rest\\AgendaUsuario\\AgendaUsuarioResourceFactory',
            'crm\\V1\\Rest\\Cron\\CronResource' => 'crm\\V1\\Rest\\Cron\\CronResourceFactory',
            'crm\\V1\\Rest\\TipoPropostaOperadora\\TipoPropostaOperadoraResource' => 'crm\\V1\\Rest\\TipoPropostaOperadora\\TipoPropostaOperadoraResourceFactory',
            'crm\\V1\\Rest\\GestoNacionalDashBoard\\GestoNacionalDashBoardResource' => 'crm\\V1\\Rest\\GestoNacionalDashBoard\\GestoNacionalDashBoardResourceFactory',
            'crm\\V1\\Rest\\ContatoCorretorBloqueio\\ContatoCorretorBloqueioResource' => 'crm\\V1\\Rest\\ContatoCorretorBloqueio\\ContatoCorretorBloqueioResourceFactory',
        ),
    ),
);
