<?php
return [
    'router' => [
        'routes' => [
            'crm.rest.auth-ldap' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/auth-ldap[/:auth_ldap_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\AuthLDAP\\Controller',
                    ],
                ],
            ],
            'crm.rest.contatos' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/contatos[/:contatos_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\Contatos\\Controller',
                    ],
                ],
            ],
            'crm.rest.usuarios' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/usuarios[/:usuarios_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\Usuarios\\Controller',
                    ],
                ],
            ],
            'crm.rest.fornecedores' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/fornecedores[/:fornecedores_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\Fornecedores\\Controller',
                    ],
                ],
            ],
            'crm.rest.corretores' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/corretores[/:corretores_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\Corretores\\Controller',
                    ],
                ],
            ],
            'crm.rest.sites' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/sites[/:sites_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\Sites\\Controller',
                    ],
                ],
            ],
            'crm.rest.interacoes' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/interacoes[/:interacoes_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\Interacoes\\Controller',
                    ],
                ],
            ],
            'crm.rest.origens-interacoes' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/origens-interacoes[/:origens_interacoes_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\OrigensInteracoes\\Controller',
                    ],
                ],
            ],
            'crm.rest.situacoes-interacoes' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/situacoes-interacoes[/:situacoes_interacoes_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\SituacoesInteracoes\\Controller',
                    ],
                ],
            ],
            'crm.rest.telefones-contato' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/telefones-contato[/:telefones_contato_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\TelefonesContato\\Controller',
                    ],
                ],
            ],
            'crm.rest.emails-contato' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/emails-contato[/:emails_contato_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\EmailsContato\\Controller',
                    ],
                ],
            ],
            'crm.rest.operadoras' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/operadoras[/:operadoras_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\Operadoras\\Controller',
                    ],
                ],
            ],
            'crm.rest.plantoes' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/plantoes[/:plantoes_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\Plantoes\\Controller',
                    ],
                ],
            ],
            'crm.rest.tipos-plantoes' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tipos-plantoes[/:tipos_plantoes_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\TiposPlantoes\\Controller',
                    ],
                ],
            ],
            'crm.rest.envio-emails' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/envio-emails[/:envio_emails_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\EnvioEmails\\Controller',
                    ],
                ],
            ],
            'crm.rest.filiais' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/filiais[/:filiais_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\Filiais\\Controller',
                    ],
                ],
            ],
            'crm.rest.permissoes-acesso' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/permissoes-acesso[/:permissoes_acesso_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\PermissoesAcesso\\Controller',
                    ],
                ],
            ],
            'crm.rest.tipos-ligacao' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tipos-ligacao[/:tipos_ligacao_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\TiposLigacao\\Controller',
                    ],
                ],
            ],
            'crm.rest.tipos-envios' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tipos-envios[/:tipos_envios_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\TiposEnvios\\Controller',
                    ],
                ],
            ],
            'crm.rest.acl' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/acl[/:acl_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\Acl\\Controller',
                    ],
                ],
            ],
            'crm.rest.agenda-usuario' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/agenda-usuario[/:agenda_usuario_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\AgendaUsuario\\Controller',
                    ],
                ],
            ],
            'crm.rest.cron' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/cron[/:cron_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\Cron\\Controller',
                    ],
                ],
            ],
            'crm.rest.tipo-proposta-operadora' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tipo-proposta-operadora[/:tipo_proposta_operadora_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\TipoPropostaOperadora\\Controller',
                    ],
                ],
            ],
            'crm.rest.gesto-nacional-dash-board' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/gesto-nacional-dash-board[/:gesto_nacional_dash_board_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\GestoNacionalDashBoard\\Controller',
                    ],
                ],
            ],
            'crm.rest.contato-corretor-bloqueio' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/contato-corretor-bloqueio[/:contato_corretor_bloqueio_id]',
                    'defaults' => [
                        'controller' => 'crm\\V1\\Rest\\ContatoCorretorBloqueio\\Controller',
                    ],
                ],
            ],
        ],
    ],
    'zf-versioning' => [
        'uri' => [
            1 => 'crm.rest.auth-ldap',
            0 => 'crm.rest.contatos',
            2 => 'crm.rest.usuarios',
            3 => 'crm.rest.fornecedores',
            4 => 'crm.rest.corretores',
            7 => 'crm.rest.sites',
            8 => 'crm.rest.interacoes',
            9 => 'crm.rest.origens-interacoes',
            10 => 'crm.rest.situacoes-interacoes',
            11 => 'crm.rest.telefones-contato',
            12 => 'crm.rest.emails-contato',
            13 => 'crm.rest.operadoras',
            14 => 'crm.rest.plantoes',
            15 => 'crm.rest.tipos-plantoes',
            17 => 'crm.rest.envio-emails',
            18 => 'crm.rest.filiais',
            19 => 'crm.rest.permissoes-acesso',
            20 => 'crm.rest.tipos-ligacao',
            21 => 'crm.rest.tipos-envios',
            22 => 'crm.rest.acl',
            23 => 'crm.rest.agenda-usuario',
            24 => 'crm.rest.cron',
            25 => 'crm.rest.tipo-proposta-operadora',
            26 => 'crm.rest.gesto-nacional-dash-board',
            27 => 'crm.rest.contato-corretor-bloqueio',
        ],
    ],
    'zf-rest' => [
        'crm\\V1\\Rest\\AuthLDAP\\Controller' => [
            'listener' => \crm\V1\Rest\AuthLDAP\AuthLDAPResource::class,
            'route_name' => 'crm.rest.auth-ldap',
            'route_identifier_name' => 'auth_ldap_id',
            'collection_name' => 'auth_ldap',
            'entity_http_methods' => [
                0 => 'PUT',
                1 => 'POST',
                2 => 'GET',
                3 => 'DELETE',
                4 => 'PATCH',
            ],
            'collection_http_methods' => [
                0 => 'POST',
                1 => 'GET',
                2 => 'PATCH',
                3 => 'DELETE',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\AuthLDAP\\AuthLDAPEntity',
            'collection_class' => \crm\V1\Rest\AuthLDAP\AuthLDAPCollection::class,
            'service_name' => 'authLDAP',
        ],
        'crm\\V1\\Rest\\Contatos\\Controller' => [
            'listener' => \crm\V1\Rest\Contatos\ContatosResource::class,
            'route_name' => 'crm.rest.contatos',
            'route_identifier_name' => 'contatos_id',
            'collection_name' => 'contatos',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'nome',
                1 => 'email',
                2 => 'telefone',
                3 => 'tipo',
                4 => 'termo',
                5 => 'groupBy',
                6 => 'idContato',
                7 => 'dataInicio',
                8 => 'dataFim',
                9 => 'tipoPlantao',
                10 => 'corretorId',
            ],
            'page_size' => '25',
            'page_size_param' => null,
            'entity_class' => \crm\Entity\Contatos::class,
            'collection_class' => \crm\V1\Rest\Contatos\ContatosCollection::class,
            'service_name' => 'contatos',
        ],
        'crm\\V1\\Rest\\Usuarios\\Controller' => [
            'listener' => \crm\V1\Rest\Usuarios\UsuariosResource::class,
            'route_name' => 'crm.rest.usuarios',
            'route_identifier_name' => 'usuarios_id',
            'collection_name' => 'usuarios',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'POST',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'email',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\Entity\\Usuarios',
            'collection_class' => \crm\V1\Rest\Usuarios\UsuariosCollection::class,
            'service_name' => 'usuarios',
        ],
        'crm\\V1\\Rest\\Fornecedores\\Controller' => [
            'listener' => \crm\V1\Rest\Fornecedores\FornecedoresResource::class,
            'route_name' => 'crm.rest.fornecedores',
            'route_identifier_name' => 'fornecedores_id',
            'collection_name' => 'fornecedores',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\Fornecedores\\FornecedoresEntity',
            'collection_class' => \crm\V1\Rest\Fornecedores\FornecedoresCollection::class,
            'service_name' => 'fornecedores',
        ],
        'crm\\V1\\Rest\\Corretores\\Controller' => [
            'listener' => \crm\V1\Rest\Corretores\CorretoresResource::class,
            'route_name' => 'crm.rest.corretores',
            'route_identifier_name' => 'corretores_id',
            'collection_name' => 'corretores',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'tipo',
                1 => 'termo',
                2 => 'filialId',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\Corretores\\CorretoresEntity',
            'collection_class' => \crm\V1\Rest\Corretores\CorretoresCollection::class,
            'service_name' => 'corretores',
        ],
        'crm\\V1\\Rest\\Sites\\Controller' => [
            'listener' => \crm\V1\Rest\Sites\SitesResource::class,
            'route_name' => 'crm.rest.sites',
            'route_identifier_name' => 'sites_id',
            'collection_name' => 'sites',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\Sites\\SitesEntity',
            'collection_class' => 'crm\\V1\\Rest\\Sites\\SitesCollection',
            'service_name' => 'sites',
        ],
        'crm\\V1\\Rest\\Interacoes\\Controller' => [
            'listener' => \crm\V1\Rest\Interacoes\InteracoesResource::class,
            'route_name' => 'crm.rest.interacoes',
            'route_identifier_name' => 'interacoes_id',
            'collection_name' => 'interacoes',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
            ],
            'collection_query_whitelist' => [
                0 => 'corretorId',
                1 => 'interacaoId',
                2 => 'idContato',
                3 => 'nome',
                4 => 'telefone',
                5 => 'email',
                6 => 'idOperadora',
                7 => 'idStatus',
                8 => 'tipoEnvio',
                9 => 'dataInicio',
                10 => 'dataFim',
                11 => 'origemTipo',
                12 => 'idOrigem',
                13 => 'pmePf',
                14 => 'empresa',
                15 => 'inativos',
                16 => 'tipo',
                17 => 'idFilial',
                18 => 'groupBy',
                19 => 'arrayDashGestor',
                20 => 'dashGestorNacional',
                21 => 'respondidas',
                22 => 'filialId',
            ],
            'page_size' => '5',
            'page_size_param' => null,
            'entity_class' => \crm\V1\Rest\Interacoes\InteracoesEntity::class,
            'collection_class' => \crm\V1\Rest\Interacoes\InteracoesCollection::class,
            'service_name' => 'interacoes',
        ],
        'crm\\V1\\Rest\\OrigensInteracoes\\Controller' => [
            'listener' => \crm\V1\Rest\OrigensInteracoes\OrigensInteracoesResource::class,
            'route_name' => 'crm.rest.origens-interacoes',
            'route_identifier_name' => 'origens_interacoes_id',
            'collection_name' => 'origens_interacoes',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\OrigensInteracoes\\OrigensInteracoesEntity',
            'collection_class' => 'crm\\V1\\Rest\\OrigensInteracoes\\OrigensInteracoesCollection',
            'service_name' => 'origensInteracoes',
        ],
        'crm\\V1\\Rest\\SituacoesInteracoes\\Controller' => [
            'listener' => \crm\V1\Rest\SituacoesInteracoes\SituacoesInteracoesResource::class,
            'route_name' => 'crm.rest.situacoes-interacoes',
            'route_identifier_name' => 'situacoes_interacoes_id',
            'collection_name' => 'situacoes_interacoes',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \crm\V1\Rest\SituacoesInteracoes\SituacoesInteracoesEntity::class,
            'collection_class' => \crm\V1\Rest\SituacoesInteracoes\SituacoesInteracoesCollection::class,
            'service_name' => 'situacoesInteracoes',
        ],
        'crm\\V1\\Rest\\TelefonesContato\\Controller' => [
            'listener' => \crm\V1\Rest\TelefonesContato\TelefonesContatoResource::class,
            'route_name' => 'crm.rest.telefones-contato',
            'route_identifier_name' => 'telefones_contato_id',
            'collection_name' => 'telefones_contato',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\TelefonesContato\\TelefonesContatoEntity',
            'collection_class' => 'crm\\V1\\Rest\\TelefonesContato\\TelefonesContatoCollection',
            'service_name' => 'telefonesContato',
        ],
        'crm\\V1\\Rest\\EmailsContato\\Controller' => [
            'listener' => \crm\V1\Rest\EmailsContato\EmailsContatoResource::class,
            'route_name' => 'crm.rest.emails-contato',
            'route_identifier_name' => 'emails_contato_id',
            'collection_name' => 'emails_contato',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \crm\V1\Rest\EmailsContato\EmailsContatoEntity::class,
            'collection_class' => \crm\V1\Rest\EmailsContato\EmailsContatoCollection::class,
            'service_name' => 'emailsContato',
        ],
        'crm\\V1\\Rest\\Operadoras\\Controller' => [
            'listener' => \crm\V1\Rest\Operadoras\OperadorasResource::class,
            'route_name' => 'crm.rest.operadoras',
            'route_identifier_name' => 'operadoras_id',
            'collection_name' => 'operadoras',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \crm\V1\Rest\Operadoras\OperadorasEntity::class,
            'collection_class' => \crm\V1\Rest\Operadoras\OperadorasCollection::class,
            'service_name' => 'operadoras',
        ],
        'crm\\V1\\Rest\\Plantoes\\Controller' => [
            'listener' => \crm\V1\Rest\Plantoes\PlantoesResource::class,
            'route_name' => 'crm.rest.plantoes',
            'route_identifier_name' => 'plantoes_id',
            'collection_name' => 'plantoes',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
                2 => 'DELETE',
            ],
            'collection_query_whitelist' => [
                0 => 'tipo',
                1 => 'termo',
                2 => 'tipoPlantao',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \crm\V1\Rest\Plantoes\PlantoesEntity::class,
            'collection_class' => \crm\V1\Rest\Plantoes\PlantoesCollection::class,
            'service_name' => 'plantoes',
        ],
        'crm\\V1\\Rest\\TiposPlantoes\\Controller' => [
            'listener' => \crm\V1\Rest\TiposPlantoes\TiposPlantoesResource::class,
            'route_name' => 'crm.rest.tipos-plantoes',
            'route_identifier_name' => 'tipos_plantoes_id',
            'collection_name' => 'tipos_plantoes',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\TiposPlantoes\\TiposPlantoesEntity',
            'collection_class' => 'crm\\V1\\Rest\\TiposPlantoes\\TiposPlantoesCollection',
            'service_name' => 'tiposPlantoes',
        ],
        'crm\\V1\\Rest\\EnvioEmails\\Controller' => [
            'listener' => \crm\V1\Rest\EnvioEmails\EnvioEmailsResource::class,
            'route_name' => 'crm.rest.envio-emails',
            'route_identifier_name' => 'envio_emails_id',
            'collection_name' => 'envio_emails',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \crm\V1\Rest\EnvioEmails\EnvioEmailsEntity::class,
            'collection_class' => \crm\V1\Rest\EnvioEmails\EnvioEmailsCollection::class,
            'service_name' => 'envioEmails',
        ],
        'crm\\V1\\Rest\\Filiais\\Controller' => [
            'listener' => \crm\V1\Rest\Filiais\FiliaisResource::class,
            'route_name' => 'crm.rest.filiais',
            'route_identifier_name' => 'filiais_id',
            'collection_name' => 'filiais',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \crm\V1\Rest\Filiais\FiliaisEntity::class,
            'collection_class' => \crm\V1\Rest\Filiais\FiliaisCollection::class,
            'service_name' => 'filiais',
        ],
        'crm\\V1\\Rest\\PermissoesAcesso\\Controller' => [
            'listener' => \crm\V1\Rest\PermissoesAcesso\PermissoesAcessoResource::class,
            'route_name' => 'crm.rest.permissoes-acesso',
            'route_identifier_name' => 'permissoes_acesso_id',
            'collection_name' => 'permissoes_acesso',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'idPerfil',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\PermissoesAcesso\\PermissoesAcessoEntity',
            'collection_class' => 'crm\\V1\\Rest\\PermissoesAcesso\\PermissoesAcessoCollection',
            'service_name' => 'permissoesAcesso',
        ],
        'crm\\V1\\Rest\\TiposLigacao\\Controller' => [
            'listener' => \crm\V1\Rest\TiposLigacao\TiposLigacaoResource::class,
            'route_name' => 'crm.rest.tipos-ligacao',
            'route_identifier_name' => 'tipos_ligacao_id',
            'collection_name' => 'tipos_ligacao',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \crm\V1\Rest\TiposLigacao\TiposLigacaoEntity::class,
            'collection_class' => \crm\V1\Rest\TiposLigacao\TiposLigacaoCollection::class,
            'service_name' => 'tiposLigacao',
        ],
        'crm\\V1\\Rest\\TiposEnvios\\Controller' => [
            'listener' => \crm\V1\Rest\TiposEnvios\TiposEnviosResource::class,
            'route_name' => 'crm.rest.tipos-envios',
            'route_identifier_name' => 'tipos_envios_id',
            'collection_name' => 'tipos_envios',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \crm\V1\Rest\TiposEnvios\TiposEnviosEntity::class,
            'collection_class' => \crm\V1\Rest\TiposEnvios\TiposEnviosCollection::class,
            'service_name' => 'tiposEnvios',
        ],
        'crm\\V1\\Rest\\Acl\\Controller' => [
            'listener' => \crm\V1\Rest\Acl\AclResource::class,
            'route_name' => 'crm.rest.acl',
            'route_identifier_name' => 'acl_id',
            'collection_name' => 'acl',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'tipo',
                1 => 'idPerfil',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'crm\\V1\\Rest\\Acl\\AclEntity',
            'collection_class' => 'crm\\V1\\Rest\\Acl\\AclCollection',
            'service_name' => 'acl',
        ],
        'crm\\V1\\Rest\\AgendaUsuario\\Controller' => [
            'listener' => \crm\V1\Rest\AgendaUsuario\AgendaUsuarioResource::class,
            'route_name' => 'crm.rest.agenda-usuario',
            'route_identifier_name' => 'agenda_usuario_id',
            'collection_name' => 'agenda_usuario',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'DELETE',
                2 => 'POST',
                3 => 'PUT',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
                2 => 'DELETE',
            ],
            'collection_query_whitelist' => [
                0 => 'idUsuario',
                1 => 'tipo',
                2 => 'dataInicio',
                3 => 'dataFim',
                4 => 'inativos',
                5 => 'concluidos',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \crm\V1\Rest\AgendaUsuario\AgendaUsuarioEntity::class,
            'collection_class' => \crm\V1\Rest\AgendaUsuario\AgendaUsuarioCollection::class,
            'service_name' => 'agendaUsuario',
        ],
        'crm\\V1\\Rest\\Cron\\Controller' => [
            'listener' => \crm\V1\Rest\Cron\CronResource::class,
            'route_name' => 'crm.rest.cron',
            'route_identifier_name' => 'cron_id',
            'collection_name' => 'cron',
            'entity_http_methods' => [
                0 => 'GET',
            ],
            'collection_http_methods' => [
                0 => 'GET',
            ],
            'collection_query_whitelist' => [
                0 => 'cron',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \crm\V1\Rest\Cron\CronEntity::class,
            'collection_class' => \crm\V1\Rest\Cron\CronCollection::class,
            'service_name' => 'cron',
        ],
        'crm\\V1\\Rest\\TipoPropostaOperadora\\Controller' => [
            'listener' => \crm\V1\Rest\TipoPropostaOperadora\TipoPropostaOperadoraResource::class,
            'route_name' => 'crm.rest.tipo-proposta-operadora',
            'route_identifier_name' => 'tipo_proposta_operadora_id',
            'collection_name' => 'tipo_proposta_operadora',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \crm\V1\Rest\TipoPropostaOperadora\TipoPropostaOperadoraEntity::class,
            'collection_class' => \crm\V1\Rest\TipoPropostaOperadora\TipoPropostaOperadoraCollection::class,
            'service_name' => 'tipoPropostaOperadora',
        ],
        'crm\\V1\\Rest\\GestoNacionalDashBoard\\Controller' => [
            'listener' => \crm\V1\Rest\GestoNacionalDashBoard\GestoNacionalDashBoardResource::class,
            'route_name' => 'crm.rest.gesto-nacional-dash-board',
            'route_identifier_name' => 'gesto_nacional_dash_board_id',
            'collection_name' => 'gesto_nacional_dash_board',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'tipo',
                1 => 'dataFim',
                2 => 'dataInicio',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \crm\V1\Rest\GestoNacionalDashBoard\GestoNacionalDashBoardEntity::class,
            'collection_class' => \crm\V1\Rest\GestoNacionalDashBoard\GestoNacionalDashBoardCollection::class,
            'service_name' => 'gestoNacionalDashBoard',
        ],
        'crm\\V1\\Rest\\ContatoCorretorBloqueio\\Controller' => [
            'listener' => \crm\V1\Rest\ContatoCorretorBloqueio\ContatoCorretorBloqueioResource::class,
            'route_name' => 'crm.rest.contato-corretor-bloqueio',
            'route_identifier_name' => 'contato_corretor_bloqueio_id',
            'collection_name' => 'contato_corretor_bloqueio',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'tipo',
                1 => 'idContato',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \crm\V1\Rest\ContatoCorretorBloqueio\ContatoCorretorBloqueioEntity::class,
            'collection_class' => \crm\V1\Rest\ContatoCorretorBloqueio\ContatoCorretorBloqueioCollection::class,
            'service_name' => 'contatoCorretorBloqueio',
        ],
    ],
    'zf-content-negotiation' => [
        'controllers' => [
            'crm\\V1\\Rest\\AuthLDAP\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Contatos\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Usuarios\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Fornecedores\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Corretores\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Sites\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Interacoes\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\OrigensInteracoes\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\SituacoesInteracoes\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\TelefonesContato\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\EmailsContato\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Operadoras\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Plantoes\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\TiposPlantoes\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\EnvioEmails\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Filiais\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\PermissoesAcesso\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\TiposLigacao\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\TiposEnvios\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Acl\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\AgendaUsuario\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\Cron\\Controller' => 'Json',
            'crm\\V1\\Rest\\TipoPropostaOperadora\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\GestoNacionalDashBoard\\Controller' => 'HalJson',
            'crm\\V1\\Rest\\ContatoCorretorBloqueio\\Controller' => 'HalJson',
        ],
        'accept_whitelist' => [
            'crm\\V1\\Rest\\AuthLDAP\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\Contatos\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\Usuarios\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\Fornecedores\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\Corretores\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\Sites\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\Interacoes\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\OrigensInteracoes\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\SituacoesInteracoes\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\TelefonesContato\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\EmailsContato\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\Operadoras\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\Plantoes\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\TiposPlantoes\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\EnvioEmails\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\Filiais\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\PermissoesAcesso\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\TiposLigacao\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\TiposEnvios\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\Acl\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\AgendaUsuario\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\Cron\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\TipoPropostaOperadora\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\GestoNacionalDashBoard\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'crm\\V1\\Rest\\ContatoCorretorBloqueio\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
        ],
        'content_type_whitelist' => [
            'crm\\V1\\Rest\\AuthLDAP\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\Contatos\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\Usuarios\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\Fornecedores\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\Corretores\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\Sites\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\Interacoes\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\OrigensInteracoes\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\SituacoesInteracoes\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\TelefonesContato\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\EmailsContato\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\Operadoras\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\Plantoes\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\TiposPlantoes\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\EnvioEmails\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\Filiais\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\PermissoesAcesso\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\TiposLigacao\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\TiposEnvios\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\Acl\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\AgendaUsuario\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\Cron\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\TipoPropostaOperadora\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\GestoNacionalDashBoard\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
            'crm\\V1\\Rest\\ContatoCorretorBloqueio\\Controller' => [
                0 => 'application/vnd.crm.v1+json',
                1 => 'application/json',
            ],
        ],
    ],
    'zf-hal' => [
        'metadata_map' => [
            'crm\\V1\\Rest\\AuthLDAP\\AuthLDAPEntity' => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.auth-ldap',
                'route_identifier_name' => 'auth_ldap_id',
                'hydrator' => \DoctrineModule\Stdlib\Hydrator\DoctrineObject::class,
            ],
            \crm\V1\Rest\AuthLDAP\AuthLDAPCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.auth-ldap',
                'route_identifier_name' => 'auth_ldap_id',
                'is_collection' => true,
            ],
            'crm\\V1\\Rest\\Contatos\\ContatosEntity' => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.contatos',
                'route_identifier_name' => 'contatos_id',
                'hydrator' => \Zend\Hydrator\ObjectProperty::class,
            ],
            \crm\V1\Rest\Contatos\ContatosCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.contatos',
                'route_identifier_name' => 'contatos_id',
                'is_collection' => true,
            ],
            'crm\\V1\\Rest\\Usuarios\\UsuariosEntity' => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.usuarios',
                'route_identifier_name' => 'usuarios_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \crm\V1\Rest\Usuarios\UsuariosCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.usuarios',
                'route_identifier_name' => 'usuarios_id',
                'is_collection' => true,
            ],
            'crm\\V1\\Rest\\Entity\\Usuarios' => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.usuarios',
                'route_identifier_name' => 'usuarios_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            'crm\\V1\\Rest\\Fornecedores\\FornecedoresEntity' => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.fornecedores',
                'route_identifier_name' => 'fornecedores_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \crm\V1\Rest\Fornecedores\FornecedoresCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.fornecedores',
                'route_identifier_name' => 'fornecedores_id',
                'is_collection' => true,
            ],
            'crm\\V1\\Rest\\Corretores\\CorretoresEntity' => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.corretores',
                'route_identifier_name' => 'corretores_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \crm\V1\Rest\Corretores\CorretoresCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.corretores',
                'route_identifier_name' => 'corretores_id',
                'is_collection' => true,
            ],
            'crm\\V1\\Rest\\Sites\\SitesEntity' => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.sites',
                'route_identifier_name' => 'sites_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            'crm\\V1\\Rest\\Sites\\SitesCollection' => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.sites',
                'route_identifier_name' => 'sites_id',
                'is_collection' => true,
            ],
            \crm\V1\Rest\Interacoes\InteracoesEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.interacoes',
                'route_identifier_name' => 'interacoes_id',
                'hydrator' => \DoctrineModule\Stdlib\Hydrator\DoctrineObject::class,
            ],
            \crm\V1\Rest\Interacoes\InteracoesCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.interacoes',
                'route_identifier_name' => 'interacoes_id',
                'is_collection' => true,
            ],
            'crm\\V1\\Rest\\OrigensInteracoes\\OrigensInteracoesEntity' => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.origens-interacoes',
                'route_identifier_name' => 'origens_interacoes_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            'crm\\V1\\Rest\\OrigensInteracoes\\OrigensInteracoesCollection' => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.origens-interacoes',
                'route_identifier_name' => 'origens_interacoes_id',
                'is_collection' => true,
            ],
            \crm\V1\Rest\SituacoesInteracoes\SituacoesInteracoesEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.situacoes-interacoes',
                'route_identifier_name' => 'situacoes_interacoes_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \crm\V1\Rest\SituacoesInteracoes\SituacoesInteracoesCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.situacoes-interacoes',
                'route_identifier_name' => 'situacoes_interacoes_id',
                'is_collection' => true,
            ],
            'crm\\V1\\Rest\\TelefonesContato\\TelefonesContatoEntity' => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.telefones-contato',
                'route_identifier_name' => 'telefones_contato_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            'crm\\V1\\Rest\\TelefonesContato\\TelefonesContatoCollection' => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.telefones-contato',
                'route_identifier_name' => 'telefones_contato_id',
                'is_collection' => true,
            ],
            \crm\V1\Rest\EmailsContato\EmailsContatoEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.emails-contato',
                'route_identifier_name' => 'emails_contato_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \crm\V1\Rest\EmailsContato\EmailsContatoCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.emails-contato',
                'route_identifier_name' => 'emails_contato_id',
                'is_collection' => true,
            ],
            \crm\V1\Rest\Operadoras\OperadorasEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.operadoras',
                'route_identifier_name' => 'operadoras_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \crm\V1\Rest\Operadoras\OperadorasCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.operadoras',
                'route_identifier_name' => 'operadoras_id',
                'is_collection' => true,
            ],
            \crm\V1\Rest\Plantoes\PlantoesEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.plantoes',
                'route_identifier_name' => 'plantoes_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \crm\V1\Rest\Plantoes\PlantoesCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.plantoes',
                'route_identifier_name' => 'plantoes_id',
                'is_collection' => true,
            ],
            'crm\\V1\\Rest\\TiposPlantoes\\TiposPlantoesEntity' => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.tipos-plantoes',
                'route_identifier_name' => 'tipos_plantoes_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            'crm\\V1\\Rest\\TiposPlantoes\\TiposPlantoesCollection' => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.tipos-plantoes',
                'route_identifier_name' => 'tipos_plantoes_id',
                'is_collection' => true,
            ],
            \crm\V1\Rest\EnvioEmails\EnvioEmailsEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.envio-emails',
                'route_identifier_name' => 'envio_emails_id',
                'hydrator' => \Zend\Hydrator\ClassMethods::class,
            ],
            \crm\V1\Rest\EnvioEmails\EnvioEmailsCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.envio-emails',
                'route_identifier_name' => 'envio_emails_id',
                'is_collection' => true,
            ],
            \crm\V1\Rest\Filiais\FiliaisEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.filiais',
                'route_identifier_name' => 'filiais_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \crm\V1\Rest\Filiais\FiliaisCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.filiais',
                'route_identifier_name' => 'filiais_id',
                'is_collection' => true,
            ],
            'crm\\V1\\Rest\\PermissoesAcesso\\PermissoesAcessoEntity' => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.permissoes-acesso',
                'route_identifier_name' => 'permissoes_acesso_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            'crm\\V1\\Rest\\PermissoesAcesso\\PermissoesAcessoCollection' => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.permissoes-acesso',
                'route_identifier_name' => 'permissoes_acesso_id',
                'is_collection' => true,
            ],
            \crm\V1\Rest\TiposLigacao\TiposLigacaoEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.tipos-ligacao',
                'route_identifier_name' => 'tipos_ligacao_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \crm\V1\Rest\TiposLigacao\TiposLigacaoCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.tipos-ligacao',
                'route_identifier_name' => 'tipos_ligacao_id',
                'is_collection' => true,
            ],
            \crm\V1\Rest\TiposEnvios\TiposEnviosEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.tipos-envios',
                'route_identifier_name' => 'tipos_envios_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \crm\V1\Rest\TiposEnvios\TiposEnviosCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.tipos-envios',
                'route_identifier_name' => 'tipos_envios_id',
                'is_collection' => true,
            ],
            'crm\\V1\\Rest\\Acl\\AclEntity' => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.acl',
                'route_identifier_name' => 'acl_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            'crm\\V1\\Rest\\Acl\\AclCollection' => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.acl',
                'route_identifier_name' => 'acl_id',
                'is_collection' => true,
            ],
            \crm\V1\Rest\AgendaUsuario\AgendaUsuarioEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.agenda-usuario',
                'route_identifier_name' => 'agenda_usuario_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \crm\V1\Rest\AgendaUsuario\AgendaUsuarioCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.agenda-usuario',
                'route_identifier_name' => 'agenda_usuario_id',
                'is_collection' => true,
            ],
            \crm\V1\Rest\Cron\CronEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.cron',
                'route_identifier_name' => 'cron_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \crm\V1\Rest\Cron\CronCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.cron',
                'route_identifier_name' => 'cron_id',
                'is_collection' => true,
            ],
            \crm\V1\Rest\TipoPropostaOperadora\TipoPropostaOperadoraEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.tipo-proposta-operadora',
                'route_identifier_name' => 'tipo_proposta_operadora_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \crm\V1\Rest\TipoPropostaOperadora\TipoPropostaOperadoraCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.tipo-proposta-operadora',
                'route_identifier_name' => 'tipo_proposta_operadora_id',
                'is_collection' => true,
            ],
            \crm\V1\Rest\GestoNacionalDashBoard\GestoNacionalDashBoardEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.gesto-nacional-dash-board',
                'route_identifier_name' => 'gesto_nacional_dash_board_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \crm\V1\Rest\GestoNacionalDashBoard\GestoNacionalDashBoardCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.gesto-nacional-dash-board',
                'route_identifier_name' => 'gesto_nacional_dash_board_id',
                'is_collection' => true,
            ],
            \crm\V1\Rest\ContatoCorretorBloqueio\ContatoCorretorBloqueioEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.contato-corretor-bloqueio',
                'route_identifier_name' => 'contato_corretor_bloqueio_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \crm\V1\Rest\ContatoCorretorBloqueio\ContatoCorretorBloqueioCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.contato-corretor-bloqueio',
                'route_identifier_name' => 'contato_corretor_bloqueio_id',
                'is_collection' => true,
            ],
            \crm\Entity\Contatos::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'crm.rest.contatos',
                'route_identifier_name' => 'contatos_id',
                'hydrator' => \DoctrineModule\Stdlib\Hydrator\DoctrineObject::class,
            ],
        ],
    ],
    'zf-apigility' => [
        'db-connected' => [],
    ],
    'zf-content-validation' => [
        'crm\\V1\\Rest\\AuthLDAP\\Controller' => [
            'input_filter' => 'crm\\V1\\Rest\\AuthLDAP\\Validator',
        ],
        'crm\\V1\\Rest\\Contatos\\Controller' => [
            'input_filter' => 'crm\\V1\\Rest\\Contatos\\Validator',
        ],
        'crm\\V1\\Rest\\Cron\\Controller' => [
            'input_filter' => 'crm\\V1\\Rest\\Cron\\Validator',
        ],
    ],
    'input_filter_specs' => [
        'crm\\V1\\Rest\\AuthLDAP\\Validator' => [
            0 => [
                'required' => true,
                'validators' => [],
                'filters' => [],
                'name' => 'usuario',
                'description' => 'Usuário do AD.',
                'error_message' => 'Informe o usuário.',
            ],
            1 => [
                'required' => true,
                'validators' => [],
                'filters' => [],
                'name' => 'password',
                'description' => 'Senha do usuario no Ad.',
                'error_message' => 'Informe a senha utilizada para logar no Ad.',
            ],
        ],
        'crm\\V1\\Rest\\Contatos\\Validator' => [
            0 => [
                'required' => true,
                'validators' => [],
                'filters' => [],
                'name' => 'nome',
                'description' => 'Nome do contato.',
                'error_message' => 'O nome é obrigatório.',
            ],
            1 => [
                'required' => false,
                'validators' => [],
                'filters' => [
                    0 => [
                        'name' => \Zend\Filter\ToInt::class,
                        'options' => [],
                    ],
                ],
                'name' => 'idade',
                'description' => 'Idade do contato, pode ser nulo.',
            ],
            2 => [
                'required' => false,
                'validators' => [],
                'filters' => [
                    0 => [
                        'name' => \Zend\Filter\ToInt::class,
                        'options' => [],
                    ],
                ],
                'name' => 'origemTipo',
                'description' => 'Tipo da origem : sites, fornecedores, outras.',
                'error_message' => 'O tipo da origem é obrigatório.',
            ],
            3 => [
                'required' => false,
                'validators' => [],
                'filters' => [],
                'name' => 'origem',
                'description' => '"origem": {
                    "id":1
                },
                 ID da origem.(valor fixo de acordo com o fornecedor)',
                'error_message' => 'Informe o ID da origem',
            ],
            4 => [
                'required' => false,
                'validators' => [],
                'filters' => [],
                'name' => 'Observação',
                'description' => 'Observação a respeito do contato. 
                    Pode ser nulo',
            ],
            5 => [
                'required' => true,
                'validators' => [],
                'filters' => [
                    0 => [
                        'name' => \Zend\Filter\ToInt::class,
                        'options' => [],
                    ],
                ],
                'name' => 'situacao',
                'description' => 'Situação do contato, valor padrão  1.',
                'error_message' => 'Informe a situação',
            ],
            6 => [
                'required' => true,
                'validators' => [],
                'filters' => [
                    0 => [
                        'name' => \Zend\Filter\ToInt::class,
                        'options' => [],
                    ],
                ],
                'name' => 'idUsuarioCad',
                'description' => 'Identificador do usuário que está efetuado o cadastro.',
                'error_message' => 'Informe o Id do usuário.',
            ],
            7 => [
                'required' => false,
                'validators' => [],
                'filters' => [
                    0 => [
                        'name' => \Zend\Filter\ToInt::class,
                        'options' => [],
                    ],
                ],
                'name' => 'idOperadora',
                'description' => 'Identificador da operada. Pode ser nulo.',
            ],
            8 => [
                'required' => false,
                'validators' => [],
                'filters' => [],
                'name' => 'tipo',
                'description' => 'Valores padrões \'pme\' e \'pf\'',
                'error_message' => 'Informe o tipo: PF ou PME',
            ],
            9 => [
                'required' => false,
                'validators' => [],
                'filters' => [],
                'name' => 'telefones',
                'description' => 'Os telefones devem vir em formato de array sem mascara : 
                "telefones":[
                   {
                    "identify":"telefone",
                    "telefone":"31234222233"
                    }
                ]',
            ],
            10 => [
                'required' => false,
                'validators' => [],
                'filters' => [],
                'name' => 'emails',
                'description' => 'Emails do contato, pode ser nullo:

                "emails":[{"identify":"email","email":"teste@teste.com"}]',
            ],
        ],
        'crm\\V1\\Rest\\Cron\\Validator' => [
            0 => [
                'required' => true,
                'validators' => [],
                'filters' => [
                    0 => [
                        'name' => \Zend\Filter\StringToLower::class,
                        'options' => [],
                    ],
                ],
                'name' => 'cron',
                'description' => 'Cron a  ser executado.',
                'error_message' => 'Informe qual rotina deseja executar.',
            ],
        ],
    ],
    'doctrine' => [
        'driver' => [
            'crm_driver' => [
                'class' => \Doctrine\ORM\Mapping\Driver\AnnotationDriver::class,
                'cache' => 'array',
                'paths' => [
                    0 => './module/crm/src/crm/Entity',
                ],
            ],
            'orm_default' => [
                'drivers' => [
                    'crm\\Entity' => 'crm_driver',
                ],
            ],
        ],
    ],
    'service_manager' => [
        'factories' => [
            \crm\V1\Rest\AuthLDAP\AuthLDAPResource::class => \crm\V1\Rest\AuthLDAP\AuthLDAPResourceFactory::class,
            \crm\V1\Rest\Contatos\ContatosResource::class => \crm\V1\Rest\Contatos\ContatosResourceFactory::class,
            \crm\V1\Rest\Usuarios\UsuariosResource::class => \crm\V1\Rest\Usuarios\UsuariosResourceFactory::class,
            \crm\V1\Rest\Fornecedores\FornecedoresResource::class => \crm\V1\Rest\Fornecedores\FornecedoresResourceFactory::class,
            \crm\V1\Rest\Corretores\CorretoresResource::class => \crm\V1\Rest\Corretores\CorretoresResourceFactory::class,
            \crm\V1\Rest\Sites\SitesResource::class => \crm\V1\Rest\Sites\SitesResourceFactory::class,
            \crm\V1\Rest\Interacoes\InteracoesResource::class => \crm\V1\Rest\Interacoes\InteracoesResourceFactory::class,
            \crm\V1\Rest\OrigensInteracoes\OrigensInteracoesResource::class => \crm\V1\Rest\OrigensInteracoes\OrigensInteracoesResourceFactory::class,
            \crm\V1\Rest\SituacoesInteracoes\SituacoesInteracoesResource::class => \crm\V1\Rest\SituacoesInteracoes\SituacoesInteracoesResourceFactory::class,
            \crm\V1\Rest\TelefonesContato\TelefonesContatoResource::class => \crm\V1\Rest\TelefonesContato\TelefonesContatoResourceFactory::class,
            \crm\V1\Rest\EmailsContato\EmailsContatoResource::class => \crm\V1\Rest\EmailsContato\EmailsContatoResourceFactory::class,
            \crm\V1\Rest\Operadoras\OperadorasResource::class => \crm\V1\Rest\Operadoras\OperadorasResourceFactory::class,
            \crm\V1\Rest\Plantoes\PlantoesResource::class => \crm\V1\Rest\Plantoes\PlantoesResourceFactory::class,
            \crm\V1\Rest\TiposPlantoes\TiposPlantoesResource::class => \crm\V1\Rest\TiposPlantoes\TiposPlantoesResourceFactory::class,
            \crm\V1\Rest\EnvioEmails\EnvioEmailsResource::class => \crm\V1\Rest\EnvioEmails\EnvioEmailsResourceFactory::class,
            \crm\V1\Rest\Filiais\FiliaisResource::class => \crm\V1\Rest\Filiais\FiliaisResourceFactory::class,
            \crm\V1\Rest\PermissoesAcesso\PermissoesAcessoResource::class => \crm\V1\Rest\PermissoesAcesso\PermissoesAcessoResourceFactory::class,
            \crm\V1\Rest\TiposLigacao\TiposLigacaoResource::class => \crm\V1\Rest\TiposLigacao\TiposLigacaoResourceFactory::class,
            \crm\V1\Rest\TiposEnvios\TiposEnviosResource::class => \crm\V1\Rest\TiposEnvios\TiposEnviosResourceFactory::class,
            \crm\V1\Rest\Acl\AclResource::class => \crm\V1\Rest\Acl\AclResourceFactory::class,
            \crm\V1\Rest\AgendaUsuario\AgendaUsuarioResource::class => \crm\V1\Rest\AgendaUsuario\AgendaUsuarioResourceFactory::class,
            \crm\V1\Rest\Cron\CronResource::class => \crm\V1\Rest\Cron\CronResourceFactory::class,
            \crm\V1\Rest\TipoPropostaOperadora\TipoPropostaOperadoraResource::class => \crm\V1\Rest\TipoPropostaOperadora\TipoPropostaOperadoraResourceFactory::class,
            \crm\V1\Rest\GestoNacionalDashBoard\GestoNacionalDashBoardResource::class => \crm\V1\Rest\GestoNacionalDashBoard\GestoNacionalDashBoardResourceFactory::class,
            \crm\V1\Rest\ContatoCorretorBloqueio\ContatoCorretorBloqueioResource::class => \crm\V1\Rest\ContatoCorretorBloqueio\ContatoCorretorBloqueioResourceFactory::class,
        ],
    ],
];
